name: Publish artifacts
on:
  push:
    branches:
      - prod
      - stage
      - dev
      - feature/*
      - bugfix/*
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew --build-cache assemble
        env:
          repositoryUser: ${{ secrets.repositoryUser }}
          repositoryPassword: ${{ secrets.repositoryPassword }}
      - name: Checkstyle
        run: ./gradlew checkstyleMain
        env:
          repositoryUser: ${{ secrets.repositoryUser }}
          repositoryPassword: ${{ secrets.repositoryPassword }}
      - name: Publish
        run: ./gradlew publish
        env:
          repositoryUser: ${{ secrets.repositoryUser }}
          repositoryPassword: ${{ secrets.repositoryPassword }}